---
title: "cvGEE: Cross-Validated Predictions for GEE"
author: "Dimitris Rizopoulos"
date: "January 29, 2020"
output:
  ioslides_presentation:
    css: pres.css
    widescreen: yes
    mathjax: default
    logo: emc.png
transition: none
runtime: shiny
---

<script type="text/x-mathjax-config">
  MathJax.Hub.Config({ TeX: { extensions: ["color.js"] }});
</script>

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
library("cvGEE")
library("geepack")
library("splines")
library("lattice")
library("MESS")
data("toenail", package = "HSAUR2")
```

# Motivation

## Grouped Categorical Data

<br/>

- Often interest in grouped non-Gaussian data
    + dichotomous/binomial
    + counts
    + ordinal
    + ...

## Grouped Categorical Data (cont'd)

- For normal data we have the multivariate version of the normal distribution
  + equivalance between marginal & mixed effects models

<br/>

- For categorical data
  + important differences between marginal and mixed models

## Grouped Categorical Data (cont'd)

- We focus on marginal models
  + proposals of multivariate distributions for categorical data (e.g., Dale, copulas, etc.)
  + difficult to fit

<br/>
  
- Liang and Zeger have come in the rescue
  
<div style="text-align:center;width:700px;border:3px solid black">
<br/>
<font color = "red" size = "6">Genaralized Estimating Equations (GEEs)</font>
<br/>
</div>

## GEEs

- GEEs have seen considerable development the last 20-30 year
  + causal inference
  + survival analysis
  + ...

## GEEs (cont'd)

- Let $Y_i$ denote a multivariate outcome with marginal mean $$\mu_i = g(X_i^\top \beta)$$

<br/>

- Estimates for $\beta$ are obtained by solving the equations
$$S(\beta) = \sum_i \frac{\partial \mu_i}{\partial \beta } \; {\color{red} V_i^{-1}} \; (Y_i - \mu_i) = 0$$

## GEEs (cont'd)

- The trick is in the definition of ${\color{red} V_i^{-1}}$
$${\color{red} V_i^{-1}} = A_i^{1/2} \; R_i(\alpha) \; A_i^{1/2}$$
where
  + $A_i= \mbox{diag}\{\mbox{var}(Y_i)^{1/2}\}$ a diagonal matrix with standard deviations
  + $R_i(\alpha)$ a *working* assumption for the pairwise correlations

## GEEs (cont'd)

- If the assumed mean structure $\mu_i$ is correctly specified, then $$\widehat{\beta} \sim \mathcal N \{ \mathbf{\beta}, \mbox{var}(\widehat{\beta})\}$$
where $$\mbox{var}(\widehat{\beta}) = V_0^{-1} V_1 V_0^{-1}$$ 
with 
  + $V_0 = \sum_{i} \frac{\partial \mu_i}{\partial \beta^\top} V_i^{-1} \frac{\partial \mu_i}{\partial\beta}$
  + $V_1 = \sum_{i} \frac{\partial \mu_i}{\partial \beta^\top} V_i^{-1} \mbox{var}(Y_i) V_i^{-1} \frac{\partial\mu_i}{\partial \beta}$

## GEEs (cont'd)

- For a dichotomous outcome
  + the mean is $$\mu_i = \pi_i = \frac{\exp(X_i^\top \beta)}{1 + \exp(X_i^\top \beta)}$$
  + the variance accounts for over-dispersion using the quasi-likelihood formulation
  $$\mbox{var}(Y_i) = {\color{red} \phi} \pi_i (1 - \pi_i)$$

## Predictions from GEEs

- A CPO project in which we fitted a GEE for count data

<br/>

- Two questions
  + Estimate $\beta$ and report results
  + calculate and <font color="red">*validate*</font> predictions

## Predictions from GEEs (cont'd)

- Predictions from a GEE are simply $$\widehat{\mu}_{ij} = g(X_{ij} \widehat{\beta})$$

<br/>

- But how to <font color="red">*properly*</font> validate these predictions?

## Predictions from GEEs (cont'd)

- We could do simple prediction error $$\sum_i\sum_j (Y_{ij} - \widehat{\mu}_{ij})^2$$

- But this is not proper for count data

## Documentation

<br/>

- Up-to-date help files

<br/>

- Dedicated website: [https://drizopoulos.github.io/cvGEE/](https://drizopoulos.github.io/cvGEE/)
    
# What the future holds...

## Future plans

- XXX

<br/>

- XXX

<br/>

- XXX
    
***

<br/> 
<br/> 

<div align = "center">
<font color = "black" size = "6">**Thank you for your attention!**</font>
</div>
<br/>
<div align = "center">
[http://www.drizopoulos.com/](http://www.drizopoulos.com/)
</div>

<br/> 
<br/>
<br/>

<div align = "center">
<font color = "black" size = "5">**These slides are available at:**</font>
</div>
<div align = "center">
<div align = "center">
[https://drizopoulos.github.io/cvGEE_presentations/](https://drizopoulos.github.io/cvGEE_presentations/)
</div>

